### ISSUE TITLE
plugin install failing with Vue 3

### ISSUE THREAD

**Issue by damonus-prime** [kazupon/vue-i18n#1065]
### vue & vue-i18n version
@vue/cli: 4.5.9
@vue-i18n:  whatever version 'vue add i18n' installs.

### Steps to reproduce
vue create i18ntest
cd i18ntest
vue add i18n

### What is Expected?
plugin installs correctly

### What is actually happening?
✔  Successfully installed plugin: vue-cli-plugin-i18n

? The locale of project localization. en
? The fallback locale of project localization. en
? The directory where store localization messages of project. It's stored under `src` directory. locales
? Enable locale messages in Single file components ? No

🚀  Invoking generator for vue-cli-plugin-i18n...
 ERROR  Error: You cannot call "get" on a collection with no paths. Instead, check the "length" property first to verify at least 1 path exists.
Error: You cannot call "get" on a collection with no paths. Instead, check the "length" property first to verify at least 1 path exists.
    at Collection.get (/Users/dfloyd/.config/yarn/global/node_modules/jscodeshift/src/Collection.js:213:13)
    at injectOptions (/Users/dfloyd/.config/yarn/global/node_modules/@vue/cli/lib/util/codemods/injectOptions.js:15:6)
    at runTransformation (/Users/dfloyd/.config/yarn/global/node_modules/vue-codemod/dist/src/run-transformation.js:61:17)
    at /Users/dfloyd/.config/yarn/global/node_modules/@vue/cli/lib/Generator.js:290:23
    at Array.forEach (<anonymous>)
    at Generator.resolveFiles (/Users/dfloyd/.config/yarn/global/node_modules/@vue/cli/lib/Generator.js:276:24)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Generator.generate (/Users/dfloyd/.config/yarn/global/node_modules/@vue/cli/lib/Generator.js:175:5)
    at async runGenerator (/Users/dfloyd/.config/yarn/global/node_modules/@vue/cli/lib/invoke.js:111:3)
    at async invoke (/Users/dfloyd/.config/yarn/global/node_modules/@vue/cli/lib/invoke.js:92:3)

**Comment by Naasi** [comment]
Same error here

**Comment by exoego** [comment]
Sorry, but vue-i18n does not support vue.js 3.x yet.
Please check https://github.com/intlify/vue-i18n-next, which support vue.js 3.x
