### ISSUE TITLE
npm install installs beta 6 instead of working stable

### ISSUE THREAD

**Issue by tvld** [kazupon/vue-i18n#126]
When I run `npm install vue-i18n`  I get a beta version 6, but it should install latest stable (which does not break my code;-) . I should stick to `  "vue-i18n": "^5.0.3",`

Note:
Although I suppose that is another issue to be reported, on vue-i18n@6.0.0-beta.1 I get:_

```log
Uncaught TypeError: _vue2.default.locale is not a function
    at eval (eval at <anonymous> (http://localhost:8080/app.js:1014:2), <anonymous>:16:17)
    at Array.forEach (native)
    at eval (eval at <anonymous> (http://localhost:8080/app.js:1014:2), <anonymous>:14:13)
    at Object.<anonymous> (http://localhost:8080/app.js:1014:2)
    at __webpack_require__ (http://localhost:8080/app.js:556:30)
    at fn (http://localhost:8080/app.js:87:20)
    at eval (eval at <anonymous> (http://localhost:8080/app.js:1026:2), <anonymous>:13:1)
    at Object.<anonymous> (http://localhost:8080/app.js:1026:2)
    at __webpack_require__ (http://localhost:8080/app.js:556:30)
    at fn (http://localhost:8080/app.js:87:20)
```

**Comment by kazupon** [comment]
Thank you for your feedback!
I fixed now.
