### ISSUE TITLE
Got error when installing using Vue CLI

### ISSUE THREAD

**Issue by darkyelox** [kazupon/vue-i18n#821]
### versions
vue = 2.6.11,  vue-i18n = 8.15.11, vue-i18n-extract = 1.0.3, vue-i18n-ts = 0.1.0

### Steps to reproduce
I simply tried to install the plugin using Vue CLI, followed the steps letting everything with its default value (english) and at the end I got the next error and the plugin didn't install:

```bash
🚀  Invoking generator for vue-cli-plugin-i18n...
 ERROR  SyntaxError: Unexpected token ] in JSON at position 472
SyntaxError: Unexpected token ] in JSON at position 472
    at JSON.parse (<anonymous>)
    at /home/diego/Documents/development/web/vuejs/darkyelox.github.io/node_modules/vue-cli-plugin-i18n/generator/index.js:138:27
    at Generator.resolveFiles (/home/diego/.nvm/versions/node/v13.7.0/lib/node_modules/@vue/cli/lib/Generator.js:299:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Generator.generate (/home/diego/.nvm/versions/node/v13.7.0/lib/node_modules/@vue/cli/lib/Generator.js:175:5)
    at async runGenerator (/home/diego/.nvm/versions/node/v13.7.0/lib/node_modules/@vue/cli/lib/invoke.js:109:3)
    at async invoke (/home/diego/.nvm/versions/node/v13.7.0/lib/node_modules/@vue/cli/lib/invoke.js:90:3)
```

### What is Expected?

Working CLI installation.

### What is actually happening?

The postinstall scripts may be failing with a bad JSON structure.

**Comment by kazupon** [comment]
Thanks for filing the issue!
Could you provide minimume reproduction code, please?

**Comment by karladler** [comment]
I have a similair error here:

> 🚀  Invoking generator for vue-cli-plugin-i18n...
 ERROR  SyntaxError: Unexpected token } in JSON at position 623
SyntaxError: Unexpected token } in JSON at position 623
    at JSON.parse (<anonymous>)
    at /Users/karl/Documents/projects/cenfood-frontend/node_modules/vue-cli-plugin-i18n/generator/index.js:138:27
    at Generator.resolveFiles (/Users/karl/.config/yarn/global/node_modules/@vue/cli/lib/Generator.js:240:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Generator.generate (/Users/karl/.config/yarn/global/node_modules/@vue/cli/lib/Generator.js:116:5)
    at async runGenerator (/Users/karl/.config/yarn/global/node_modules/@vue/cli/lib/invoke.js:133:3)
    at async invoke (/Users/karl/.config/yarn/global/node_modules/@vue/cli/lib/invoke.js:117:3)

**Comment by exoego** [comment]
> SyntaxError: Unexpected token ] in JSON 

The error message indicates that you have broken configs, as @karladler suggested.
Could you share actual commands to install, and the broken config?

**Comment by kazupon** [comment]
close due to in-activity
