### ISSUE TITLE
Crashes when fallbackLocale is not provided

### ISSUE THREAD

**Issue by rchl** [kazupon/vue-i18n#849]
**This is not a bug** but it's a behavior change for `nuxt-i18n` so I'm creating it for your consideration.

### vue & vue-i18n version
**vue-i18n**: 8.17.3

### Reproduction Link
https://jsfiddle.net/4m5yaq1e/5/
(It doesn't reproduce any issue but shows the sort of configuration that `nuxt-i18n` has a problem with)

### Steps to reproduce
In `nuxt-i18n` I have one test that started failing with latest version of `vue-i18n`.

That test asserts that `vue-i18n` with an empty configuration doesn't cause any issues but it started crashing.

An empty configuration would normally not cause issues in `vue-i18n` but, for specific reasons, I'm explicitly [altering `i18n.locale` and `i18n.fallbackLocale` to `null` at runtime](https://github.com/nuxt-community/nuxt-i18n/blob/f7dd69f2e5ee50f633797d4319a561b18bbb9bdc/src/plugins/main.js#L195-L197) when no values were provided for those.

`vue-i18n` didn't have problems with that before, until #138 which added code that crashes when locale/fallbackLocale is null.

The stack trace is something like this:
```
ERROR  Cannot read property 'split' of null                                                                                                                                                                10:01:00

  at VueI18n._appendLocaleToChain (node_modules/vue-i18n/dist/vue-i18n.common.js:1518:23)
  at VueI18n._appendBlockToChain (node_modules/vue-i18n/dist/vue-i18n.common.js:1531:19)
  at VueI18n._getLocaleChain (node_modules/vue-i18n/dist/vue-i18n.common.js:1555:20)
  at VueI18n._translate (node_modules/vue-i18n/dist/vue-i18n.common.js:1603:20)
  at VueI18n._t (node_modules/vue-i18n/dist/vue-i18n.common.js:1629:18)
```

### What is Expected?
I don't expect this to be treated as a bug as the usage is somewhat non-standard and not in line with documentation, but also it probably would be easy to change the code to not crash in this situation.

**Comment by rchl** [comment]
I can work around that on my side by using some "random" string value rather than `null`. The point of me doing that is to initialize those to something that is not likely to match any of the locales provided explicitly by the user.

**Comment by rchl** [comment]
Thanks for considering it but I've realized I can use empty string instead of null which will fix my issue and will be in line with the expected type of the locale.
