### ISSUE TITLE
Error: You cannot call "get" on a collection with no paths. Instead, check the "length" property first to verify at least 1 path exists.

### ISSUE THREAD

**Issue by helloZh4n** [kazupon/vue-i18n#992]
A reporter did not know the reason for this mistake

**Comment by exoego** [comment]
Could you respect the issue template?

**Comment by helloZh4n** [comment]
If the problem can't be solved, that's the problem. For me, it's a problem, although it may be a problem for you

**Comment by helloZh4n** [comment]
> 您可以尊重问题模板吗？
If the problem can't be solved, that's the problem. For me, it's a problem, although it may be a problem for you

**Comment by Silbad** [comment]
Hello, I have the same pb with vue-cli + vue 3
```
�  Invoking generator for vue-cli-plugin-i18n...
 ERROR  Error: You cannot call "get" on a collection with no paths. Instead, check the "length" property first to verify at least 1 path exists.
```

**Comment by waruyama** [comment]
I have the same problem with Vue 3 and Vue-cli (on Windows 10).

Here is the complete error stack:

```
Error: You cannot call "get" on a collection with no paths. Instead, check the "length" property first to verify at least 1 path exists.
    at Collection.get (C:\Users\currentuser\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\jscodeshift\src\Collection.js:213:13)
    at injectOptions (C:\Users\currentuser\AppData\Roaming\npm\node_modules\@vue\cli\lib\util\codemods\injectOptions.js:15:6)
    at runTransformation (C:\Users\currentuser\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\vue-codemod\dist\src\run-transformation.js:61:17)
    at C:\Users\currentuser\AppData\Roaming\npm\node_modules\@vue\cli\lib\Generator.js:290:23
    at Array.forEach (<anonymous>)
    at Generator.resolveFiles (C:\Users\currentuser\AppData\Roaming\npm\node_modules\@vue\cli\lib\Generator.js:276:24)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Generator.generate (C:\Users\currentuser\AppData\Roaming\npm\node_modules\@vue\cli\lib\Generator.js:175:5)
    at async runGenerator (C:\Users\currentuser\AppData\Roaming\npm\node_modules\@vue\cli\lib\invoke.js:111:3)
    at async invoke (C:\Users\currentuser\AppData\Roaming\npm\node_modules\@vue\cli\lib\invoke.js:92:3)
```

**Comment by kazupon** [comment]
See the link:
vue-cli-plugin-i18n hasn't been support for Vue 3...
https://github.com/kazupon/vue-cli-plugin-i18n/issues/143
